### PR TITLE
IDE session at NTNU

### PR DESCRIPTION
**Pull request by blindij**
Updated IDE session with new figures from PyCharm and simpler code examples.

### CODE REVIEW

**Comment by bast** [comment]
Looks good! Can the debugging demo work fine also without the Class and the `__main__` part? The less we need to explain/understand the better. But perhaps by removing it the point of the exercise breaks down? I think the stepping/debugging could possibly be done with simple functions without any classes.

**Comment by blindij** [comment]
You are right. I can make it as a function and drop the class. Simpler and easier to understand

**Comment by blindij** [comment]
Changed the code to only use functions. Kept the __main__.

**Comment by bast** [comment]
Thanks! Can you please test on Python 3? I expect the print function to fail then.

**Comment by blindij** [comment]
Tested on Python3. It works except for the print statements.

**Comment by bast** [comment]
OK - great. Let's fix those and then we can merge this. Thank you!

**Comment by blindij** [comment]
Added commented print() for python 3  in code examples

**Comment by bast** [comment]
I will submit a patch in a moment and also give you write perms.

**Pull request merged**
